sequenceDiagram
    actor Użytkownik as Użytkownik
    Użytkownik->>Biletomat: Pokaż dostępne języki
    Biletomat-->>Użytkownik: 
    Użytkownik->>Biletomat: Wybierz język
    Biletomat->>Biletomat: Zmiana języka interfejsu
    Biletomat-->>Użytkownik: 
