sequenceDiagram
    %% Diagram: D1 - Sprawdzenie ważności biletu
    actor Uzytkownik as Użytkownik
    participant SystemBiletowy as System Biletowy
    Uzytkownik->>SystemBiletowy: Sprawdź ważność biletu
    SystemBiletowy-->>Uzytkownik: Informacja o statusie biletu