flowchart TD

subgraph Biletomat ["Biletomat"]
    B1(Sprzedaż biletu)
    B2(Zmiana języka)
    B3(Wyświetlenie ofert)
end

subgraph SystemTransakcyjny ["System Transakcyjny"]
    C1(Generowanie raportow)
end

subgraph SystemBiletowy ["System Biletowy"]
    D1(Sprawdzenie ważności biletu)
    D2(Aktualizuj listę biletów)
end

subgraph SystemWsparciaTechnicznego ["Wsparcie IT"]
    E1(Pobrabnie stanu biletomatow)
    E2(ZobCENIE alertow o bledach)
end

subgraph Administrator ["Administrator Systemu"]
    F1(Zdalna aktualizacja oprogramowania biletomatow)
end